CREATE TABLE TB_ROLE (
    ID INT PRIMARY KEY,
    AUTHORITY VARCHAR(255)
);

INSERT INTO tb_role (ID, AUTHORITY) VALUES (1, 'ESTUDANTE');
INSERT INTO tb_role (ID, AUTHORITY) VALUES (2, 'INSTRUTOR');
INSERT INTO tb_role (ID, AUTHORITY) VALUES (3, 'ADMIN');
