CREATE TABLE TB_ROLE (
    ID INT PRIMARY KEY,
    AUTHORITY VARCHAR(255)
);

INSERT INTO tb_role (AUTHORITY) VALUES ('ROLE_ESTUDANTE');
INSERT INTO tb_role (AUTHORITY) VALUES ('ROLE_INSTRUTOR');
INSERT INTO tb_role (AUTHORITY) VALUES ('ROLE_ADMIN');
